### ISSUE TITLE
Update Sample with Non-PermisoActivity Subclass Example

### ISSUE THREAD

**Issue by ScottCooper92** [greysonp/permiso#1]
Thanks for the library, I've been trying to get it working without subclassing PermisoActivity and can't get the Dialogs to show.

I've added the setActivity(this) in onCreate but it's unclear whether the permissions are still requested in the same manner. Could you update the sample app with an example?

Edit: I've managed to get it working now, I wasn't calling callback.onRationalProvided(). An updated sample might be beneficial to someone else however.

**Comment by greysonp** [comment]
Ah yes, that's a good idea, thank you! I do currently show how to do it in the FAQ section of the Readme, but I'll add an actual full code example in the demo app when I get home. Thanks!
