### ISSUE TITLE
Problem with multiple permissions

### ISSUE THREAD

**Issue by ssubraveti** [greysonp/permiso#12]
I cannot request more than two permissions in the way suggested in the docs.
Here's my permission request code:

public boolean reqPerms()
    {
        Permiso.getInstance().requestPermissions(new Permiso.IOnPermissionResult() {
            @Override
            public void onPermissionResult(Permiso.ResultSet resultSet) {
                if (resultSet.isPermissionGranted(Manifest.permission.READ_SMS)){//Some code}
                        if(resultSet.isPermissionGranted(Manifest.permission.READ_CALL_LOG)){//Some code}
                        if(resultSet.isPermissionGranted(Manifest.permission.READ_PHONE_STATE)){//Some code}
               if(resultSet.isPermissionGranted(Manifest.permission.INTERNET)){//Some code}
                if(resultSet.isPermissionGranted(Manifest.permission.ACCESS_FINE_LOCATION)){}
                    //tv.setText("Permissions granted");
            }
            @Override
            public void onRationaleRequested(Permiso.IOnRationaleProvided callback, String... permissions) {
                Permiso.getInstance().showRationaleInDialog("Permissions req", "App won't function without permissions!", null, callback);
            }
        }, Manifest.permission.READ_SMS, Manifest.permission.READ_PHONE_STATE,Manifest.permission.READ_CALL_LOG,Manifest.permission.INTERNET);
        return true;
    }

**Comment by greysonp** [comment]
I just tested your snippet and it works fine for me. Have you made sure to declare your permissions in your AndroidManifest.xml? That's a regular thing you have to do with permissions. I'll add that to the readme.

**Comment by greysonp** [comment]
Done.

**Comment by greysonp** [comment]
I'm going to assume this was your issue, as I couldn't reproduce it otherwise with your snippet. Please re-open this if you're still having difficulties!

Thanks!

**Comment by ssubraveti** [comment]
Hello Greyson
I've fixed my code. I didn't realize that permissions were being grouped.

**Comment by ssubraveti** [comment]
Thanks for taking your time to resolve the issue!
