### ISSUE TITLE
showRationaleInDialog doesn't remove/replace existing dialog

### ISSUE THREAD

**Issue by paulpv** [greysonp/permiso#14]
showRationaleInDialog is a simple method that creates and shows a new instance of PermisoDialogFragment (and also sets a callback) with a tag of PermisoDialogFragment.TAG.

If there is an existing dialog showing with a tag of PermisoDialogFragment.TAG, then this will show multiple dialogs.

showRationaleInDialog should first call FragmentManager#findFragmentByTag(String tag) and dismiss that dialog.

**Comment by paulpv** [comment]
Also/FYI, I question if "dialogFragment.setOnCloseListener(...)" will survive a screen rotation...but that is a separate issue.

**Comment by paulpv** [comment]
I don't quite understand how, but setOnCloseListener seems to handle rotation just fine.
I would think a reference to a callback would not be retained when the DialogFragment is recreated after a rotation.
This goes against how I thought Fragments worked...unless something changed since I last groked how they worked.

**Comment by greysonp** [comment]
To prevent the listener being lost on rotation, I call `setRetainInstanceState(true)`.
https://github.com/greysonp/permiso/blob/master/permiso/src/main/java/com/greysonparrelli/permiso/PermisoDialogFragment.java#L56

**Comment by paulpv** [comment]
Thanks! I see that now in the comments! :)
