### ISSUE TITLE
PermisoDialogFragment custom theme

### ISSUE THREAD

**Issue by Knuth75** [greysonp/permiso#23]
Add the option to customize the theme in the AlertDialog builder in the onCreateDialog to fix the still not resolved issue of the colorAccent in the AppCompat dialogs.

Thanks.

**Comment by greysonp** [comment]
Working on it!

**Comment by greysonp** [comment]
Hey, added support! I haven't cut a new version for this, but I added instructions in the README on how to add the dev release to your project via jitpack.io. Let me know if you have any questions!
