### ISSUE TITLE
Unregister Activity

### ISSUE THREAD

**Issue by ScottCooper92** [greysonp/permiso#6]
Leak Canary is detecting memory leaks with Permiso because it stores a reference to the Activity, preventing it from being GC'd. You can get around this by calling _Permiso.getInstance().setActivity(null)_
in _onDestroy_ but ideally there could be a _Permiso.getInstance().unregisterActivity()_ or something along those lines.

**Comment by greysonp** [comment]
Yeah, I've actually been meaning to look into only holding weak references to the activity as well, that way Permiso would ditch the reference when the system does. I'll try that out later, and if it doesn't work out the way I hope, I'll look into adding this method. Thanks!
