### ISSUE TITLE
Deny doesn't call onPermissionResult

### ISSUE THREAD

**Issue by behelit** [greysonp/permiso#7]
I'm using permiso in a fragment within a tablayout `Fragment extends ListFragment`
In the `onResume` I am performing the permission request:

```
@Override
    public void onResume()
    {
        super.onResume();

        Permiso.getInstance().setActivity(getActivity());

        Log.e(TAG, "Requesting Contact Permission");

        Permiso.getInstance().requestPermissions(new Permiso.IOnPermissionResult()
        {
            @Override
            public void onPermissionResult(Permiso.ResultSet resultSet)
            {
                if(resultSet.areAllPermissionsGranted())
                {
                    Log.e(TAG, "Contact Permission Granted");
                }
                else
                {
                    Log.e(TAG, "Contact Permission Denied");
                }
            }

            @Override
            public void onRationaleRequested(Permiso.IOnRationaleProvided callback, String... permissions)
            {
                Permiso.getInstance().showRationaleInDialog(getText(R.string.contacts_string_contactpermissiontitle).toString(), getText(R.string.contacts_string_contactpermissionrationale).toString(), null, callback);
            }
        }, Manifest.permission.WRITE_CONTACTS);
    }
```

The onPermissionResult is never called if the 'Deny' option is pressed.
It all works correctly if 'Allow' is pressed.

Please note, the contact fragment is not the default tab but it is next to it so it gets loaded anyway.

I have also set:

```
@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults)
    {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        Permiso.getInstance().onRequestPermissionResult(requestCode, permissions, grantResults);
    }
```

and

```
@Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        // Setup permission library
        Permiso.getInstance().setActivity(getActivity());
    }
```

**Comment by greysonp** [comment]
Hi @behelit, I'm looking into it! I'm doing my best to replicate your code setup. Here are some questions:
1. In your logs, do you see anything with the tag "Permiso" that says "onRequestPermissionResult() was given an unrecognized request code." after you deny the permission?
2. Is the code your showing me in the fragment? If so, you shouldn't be calling `Permiso.setActivity()`. That only needs to be done at the activity level. The easy way to do it is by having your activity subclass PermisoActivity. If you don't want to do that, you just have to make sure your activity calls the correct methods as specified in the README (short version: call `Permiso.setActivity()` in `onCreate()` and `onResume()`, and forward the results of `onRequestPermissionsResult()` to `Permiso.onRequestPermissionResult()`. Nothing needs to be done in the fragment itself.
3. Your last sentence hinted that this fragment is in a tab group. Is that correct?

**Comment by greysonp** [comment]
So, I just created a simple Activity-Fragment setup, and I put this code in the Fragment's `onResume()`, and I can't replicate your issue. However, I'm guessing your issue is really in the details, something to do with either your activity setup or the tab group. 

Also, can I get the details of the phone and android version you're testing on?

**Comment by greysonp** [comment]
Oh, also, when you do get the 'deny' button working, you're going to run into an issue. The user will get stuck in a deny loop. After they deny the permission, `onResume()` is called, triggering another permission request, showing the rationale dialog, which when dismissed triggers another `onResume()`, etc, etc getting the user stuck in a loop.

Doing this in `onStart()` may be a better choice.

**Comment by greysonp** [comment]
Anyway, this is the app I created to in the process of trying to mimic your setup. Feel free to make changes to try to reproduce the issue. I'll add you as a collaborator.

https://github.com/greysonp/permiso-debug-app

**Comment by behelit** [comment]
Thanks @greysonp, I will try out your suggestions relating to the parent activity (and onStart) and give an update.
I think that sounds like the most probably cause.

**Comment by behelit** [comment]
Yes, that was the problem.
I moved the Permiso instance configurations into the tab activity and everything is working as expected.
Thanks for your help. This library is awesome.

**Comment by greysonp** [comment]
That's great to hear, and thank you!
