### ISSUE TITLE
Never Show Request Again

### ISSUE THREAD

**Issue by NoelChew** [greysonp/permiso#9]
Any way we can find out that user has checked "Never Show Again" when denying request?

**Comment by greysonp** [comment]
There currently isn't a way. If a user has checked "never show again", then when you request the permission, you will immediately get a callback saying that permission has been denied, and you should be able to just handle it with your normal "denied" flow. 

What's your use case? Maybe it's worth adding.

**Comment by NoelChew** [comment]
If user checks "Never Show Again" when denying, we can show a different message to them.

Here is a message that is shown when user denies and checks "Never Show Again":

> The app permissions can be configured in phone Settings.

I have compared libraries from Dexter and PermissionDispatcher, they both have this feature.
I am using Permiso because it is the only one working fine for me.

**Comment by NoelChew** [comment]
```
private boolean isPermissionPermanentlyDenied(String permission) {
    if (checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED &&
    !shouldShowRequestPermissionRationale(permission)) {
        return true;
    } else {
        return false;
    {
}
```

I have not tested this code. But this might be it. Referred from:
[Everything every Android Developer must know about new Android's Runtime Permission](http://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en)

**Comment by greysonp** [comment]
Yes, in permiso, a temporary workaround would be to do the following (note: this is untested):

```
Permiso.getInstance().requestPermissions(new Permiso.IOnPermissionResult() {

    private boolean wasRationaleRequested = false;

    @Override
    public void onPermissionResult(Permiso.ResultSet resultSet) {
        if (resultSet.areAllPermissionsGranted()) {
            // Permission granted!
        } else if (wasFirstRequest || wasRationaleRequested) {
            // Permission denied.
        } else if (!wasFirstRequest) {
            // Permission permanently denied.
        }
    }

    @Override
    public void onRationaleRequested(Permiso.IOnRationaleProvided callback, String... permissions) {
        wasRationaleRequested = true;
        Permiso.getInstance().showRationaleInDialog("Title", "Message", null, callback);
    }
}, Manifest.permission.READ_EXTERNAL_STORAGE);
```

You'd need to keep track of whether or not this was the first request (the `wasFirstRequest` var in that snippet) through shared prefs or something. The idea here is that if a permission is ever denied after the first request without Android requesting a rationale, then they must have check the "Never Show Again" box.

It's important to note that this will only detect permission requests that were denied because the user _previously_ checked "Never Show Again". There's no way to detect if the user check "Never Show Again" for the _current_ request.

**Comment by greysonp** [comment]
I'm thinking we could add a method to the `Permiso.ResultSet` that would allow you to check if your permission was permanently denied. e.g. `resultSet.isPermissionPermanentlyDenied(Manifest.Permission.READ_CONTACTS)`. 

I don't think it'd be that bad to implement, it'd just screw up `Permiso.ResultSet#toMap()`, since that currently returns a map of strings to booleans, and it'd now have to return a map of strings to enums or what have you.

I'll look into it.

**Comment by NoelChew** [comment]
Thanks!

**Comment by greysonp** [comment]
I wanted to update my snippet from earlier to reflect a simpler way of doing things. 

```
Permiso.getInstance().requestPermissions(new Permiso.IOnPermissionResult() {
    @Override
    public void onPermissionResult(Permiso.ResultSet resultSet) {
        if (resultSet.areAllPermissionsGranted()) {
            // Permission granted!
        } else if (ActivityCompat.shouldShowRequestPermissionRationale(MyActivity.this, Manifest.permission.READ_EXTERNAL_STORAGE) {
            // Permission denied.
        } else {
            // Permission permanently denied.
        }
    }

    @Override
    public void onRationaleRequested(Permiso.IOnRationaleProvided callback, String... permissions) {
        Permiso.getInstance().showRationaleInDialog("Title", "Message", null, callback);
    }
}, Manifest.permission.READ_EXTERNAL_STORAGE);
```

No need to know whether or not this was the first time you requested the permission, because at the point you check `shouldShowRequestPermissionRationale()`, it's already been asked once, so if it was just denied and you also shouldn't show rationale in the future, then you know they checked "Never Show Again". Major oversight on my part, sorry for the complication. I hope to have this built into `Permiso.ResultSet` by the end of the weekend.

Thanks!

**Comment by NoelChew** [comment]
Thank you.

However, your method doesn't work for an array of permissions.
When more than one permissions are involved, the coding becomes more complex.

**Comment by greysonp** [comment]
Sure, so this can be as complicated as you want it to be. If you want custom "Never Show Again" logic depending on which permission in the set was denied (e.g. you want to show a custom message), then yeah, you're going to have a series of `if` statements. 

If you're looking to check if _any_ of the permissions were permanently denied, you can just do a simple check in a `for` loop. 

```
public boolean isAnyPermissionPermanentlyDenied(Activity activity, String... permissions) {
    for (String permission : permissions) {
        if (!ActivityCompat.shouldShowRequestPermissionRationale(activity,  permission) {
           return true;
        }
    }
    return false;
}
```

Again, I hope to implement this soon (busy week/weekend, just moved into a new place), this is just a temporary workaround. The `Permiso.ResultSet` object will be given two new methods: `isPermissionPermanentlyDenied(String permission)` and `isAnyPermissionPermanentlyDenied()`.

**Comment by NoelChew** [comment]
```
public static void startInstalledAppDetailsActivity(final Activity context) {
        if (context == null) {
            return;
        }
        final Intent i = new Intent();
        i.setAction(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        i.addCategory(Intent.CATEGORY_DEFAULT);
        i.setData(Uri.parse("package:" + context.getPackageName()));
        i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        i.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
        i.addFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
        context.startActivity(i);
    }
```

In the event of permission denied with "Never Show Again", you can use the code above the start app Settings. Can consider adding this "Settings" button into PermisoDialog if user has denied permanently.

**Comment by NoelChew** [comment]
v 0.2.0 doesn't work.
onPermissionResult does not get called at all, whether user Allows, Deny or Deny with Never Show Again.

**Comment by greysonp** [comment]
Can you show me your code snippet? Everything works fine in the sample app. 

Try copy-pasting a snippet from the sample app into your app and see if it works: [link](https://github.com/greysonp/permiso/blob/master/app/src/main/java/com/greysonparrelli/permisodemo/MainActivity.java#L65)

If things still aren't working when you think they should be, open up another issue and we'll get this fixed up :)

**Comment by NoelChew** [comment]
```
public static void getPermissionSaveMediaToStorage(final Context context, final PermissionListener listener) {
        ArrayList<Integer> rationaleStringResourceArrayList = new ArrayList<>();
        rationaleStringResourceArrayList.add(R.string.permission_rationale_feature_save_media_to_storage);
        getPermission(context, listener, rationaleStringResourceArrayList, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE);
    }

public static void getPermission(final Context context, final PermissionListener listener, final ArrayList<Integer> rationaleStringResourceArrayList, final String... permissions) {
        Permiso.getInstance().requestPermissions(new Permiso.IOnPermissionResult() {
            @Override
            public void onPermissionResult(Permiso.ResultSet resultSet) {
                boolean hasPermanentlyDeniedPermission = false;
                if (resultSet.areAllPermissionsGranted()) {
                    listener.onPermissionGranted();
                } else {
                    ArrayList<String> permissionsDeniedArrayList = new ArrayList<>();
                    for (String strPermission : permissions) {
                        if (resultSet.toMap().containsKey(strPermission)) {
                            if (resultSet.toMap().get(strPermission) == Permiso.Result.DENIED) {
                                permissionsDeniedArrayList.add(strPermission);
                            } else if (resultSet.toMap().get(strPermission) == Permiso.Result.PERMANENTLY_DENIED) {
                                permissionsDeniedArrayList.add(strPermission);
                                hasPermanentlyDeniedPermission = true;
                            }
                        }
                    }
                    AlertDialog.Builder builder = new AlertDialog.Builder(context);
                    builder.setTitle(R.string.app_name)
                            .setMessage(
                                    context.getString(R.string.permission_denied_general) +
                                            getPermissionGroupStrings(context, permissionsDeniedArrayList) +
                                            context.getString(R.string.permission_denied_general_part2) +
                                            formatRationaleStrings(context, rationaleStringResourceArrayList) +
                                            context.getString(R.string.permission_denied_general_instructions))
                            .setCancelable(false);
                    if (hasPermanentlyDeniedPermission) {
                        builder.setNegativeButton(R.string.ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                listener.onPermissionPermanentlyDenied();
                            }
                        })
                                .setPositiveButton(R.string.settings, new DialogInterface.OnClickListener() {
                                    @Override
                                    public void onClick(DialogInterface dialog, int which) {
                                        listener.onPermissionPermanentlyDenied();
                                        PermissionUtil.startInstalledAppDetailsActivity(context);
                                    }
                                });

                    } else {
                        builder.setNeutralButton(R.string.ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                listener.onPermissionDenied();
                            }
                        });
                    }
                    builder.create()
                            .show();
                }
            }

        @Override
        public void onRationaleRequested(Permiso.IOnRationaleProvided callback, String... permissions) {
                Permiso.getInstance().showRationaleInDialog(context.getString(R.string.app_name),
                        context.getString(R.string.permission_rationale_general) +
                                getPermissionGroupStrings(context, permissions) +
                                context.getString(R.string.permission_rationale_general_part2) +
                                formatRationaleStrings(context, rationaleStringResourceArrayList),
                        null,
                        callback);
            }
        }, permissions);
    }

public interface PermissionListener {
        void onPermissionGranted();

        void onPermissionDenied();

        void onPermissionPermanentlyDenied();

    }
```

Some methods to generate dialog messages are missing, but they are not required to reproduce the error.

**Comment by NoelChew** [comment]
I am sorry. I made some mistakes on my part. Your library is working as expected.

**Comment by greysonp** [comment]
Ok cool :)
